#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Set default values for optional config panel settings if not provided
sync_user_1=${sync_user_1:-}
sync_user_2=${sync_user_2:-}
sync_user_3=${sync_user_3:-}
sync_user_4=${sync_user_4:-}
sync_user_5=${sync_user_5:-}
max_sync_payload_megs=${max_sync_payload_megs:-100}

# Store settings
ynh_app_setting_set --app=$app --key=sync_user_1 --value="$sync_user_1"
ynh_app_setting_set --app=$app --key=sync_user_2 --value="$sync_user_2"
ynh_app_setting_set --app=$app --key=sync_user_3 --value="$sync_user_3"
ynh_app_setting_set --app=$app --key=sync_user_4 --value="$sync_user_4"
ynh_app_setting_set --app=$app --key=sync_user_5 --value="$sync_user_5"
ynh_app_setting_set --app=$app --key=max_sync_payload_megs --value="$max_sync_payload_megs"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

#Use venv to install pip requirements - Inspired from https://github.com/YunoHost-Apps/pyinventory_ynh/blob/master/scripts/install
ynh_script_progression --message="Installing pip requirements..." --weight=70
# Always recreate everything fresh with current python version
if [ -d "${install_dir}/venv" ] ; then
	ynh_secure_remove "${install_dir}/venv"
fi

# Skip pip because of: https://github.com/YunoHost/issues/issues/1960
python3 -m venv --without-pip "${install_dir}/venv"
chown -R "$app:" "$install_dir"

#run source in a 'sub shell'
(
	set +o nounset
	source "${install_dir}/venv/bin/activate"
	set -o nounset
	ynh_exec_as $app $install_dir/venv/bin/python3 -m ensurepip # requires python-venv package
	ynh_exec_as $app $install_dir/venv/bin/pip3 install --no-cache-dir --upgrade anki
)

ynh_add_config --template="anki-syncserver" --destination="${install_dir}/anki-syncserver"
chmod +x "${install_dir}/anki-syncserver"
chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create log directory
mkdir -p /var/log/$app
chown -R $app:$app /var/log/$app

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config with environment variables
configure_systemd_service

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

yunohost service add $app --description="Anki Sync Server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last

